# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  
commands:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy-test:
    steps:
      - run: npm run cdk deploy --require-approval never dinero-tst
  deploy-prod:
    steps:
      - run: npm run cdk deploy --require-approval never dinero

jobs:
  build:
    executor: aws-cli/default
    steps: 
      - build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-test:
    branches:
      ignore:
        - master
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - attach_workspace:
        at: .
      - deploy-test

  deploy-prod:
    branches:
      only:
        - master
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - attach_workspace:
        at: .
      - deploy-prod

workflows:
  build:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
      - deploy-prod:
          requires:
            - build